version: '3.8'

services:
  backend:
    build: ./producthub
    ports:
      - "8000:8000"
    volumes:
      - ./producthub:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend